### PR TITLE
Add way to avoid reboots with a tpm.

### PR DESCRIPTION
**Pull request by GZibrat**
On GCE we have the TPM enabled by default so we hit this reboot on every VM start. Some VM types have a very expensive reboot so we'd like to avoid this reboot if possible.

The mechanism here does that by not having the fallback change the boot order so that it always remains in the boot path. This should keep TPM measurements stable to make the reboot not needed.

author: Gary Zibrat <gzibrat@google.com>

### CODE REVIEW

**Comment by julian-klode** [comment]
We probably should avoid this workaround, options are bad (who tests them, why do systems behave differently, etc), and the right approach to this is integrating the fallback into shim directly which is already planned.

**Comment by GZibrat** [comment]
https://github.com/rhboot/shim/issues/429

Perhaps this is the issue to track?

I am happy to work on it if it doesn't seem terribly complicated or if I can get some pointers on the general idea.

**Comment by GZibrat** [comment]
@vathpela 

Any answers or thoughts on this?

**Comment by vathpela** [comment]
Hopefully this branch https://github.com/vathpela/mallory/tree/merge-mm-and-fb-into-shim (still very much a work in progress) should address the issue for you?  But yes, this is issue #429

**Pull request closed without merging**
