### PR TITLE
Improve adding sbat section example in SBAT.md

### PR DESCRIPTION
**Pull request by bernhardreiter**
* Add `--adjust-section-vma .sbat+10000000` to the `objcopy` example command to make sure
   to add the .sbat section to the end of the binary and avoid problems like #376

### CODE REVIEW

**Comment by vathpela** [comment]
Please don't push merges into the PR, it makes it impossible to figure out what's going on.

**Comment by bernhardreiter** [comment]
@vathpela I usually look at the diff (which is very short for this pull-request) and had hoped that merging changes in from main would make acceptance easier. (Won't do it again in this repo.)

**Comment by jsetje** [comment]
@bernhardreiter I've looked at this twice now, and it seems like this is something you had to do due to something specific to your binary. I'm not sure this makes sense as a general recommendation.

**Comment by bernhardreiter** [comment]
> @bernhardreiter I've looked at this twice now, 

@jsetje thanks for having taken the time! 

> and it seems like this is something you had to do due to something specific to your binary. I'm not sure this makes sense as a general recommendation.

Being no expert, I do not know enough to decide this. From the descriptions in #376, it seems that I wasn't the only one with the issue and some `objcopy` binaries may need this option. I have suggesting it, because it seems harmless to give the option just in case someone has an `objcopy` binary that needs it.

**Comment by vathpela** [comment]
I don't think this is an ongoing issue, so I'm closing this.

**Pull request closed without merging**
