### PR TITLE
Add spec-based PCR7 support

### PR DESCRIPTION
**Pull request by mjg59**
Add support for measuring the Shim signing state into PCR7 in the same way that the firmware does in Secure Boot mode.

### CODE REVIEW

**Comment by mjg59** [comment]
Done.

**Comment by martinezjavier** [comment]
@mjg59 hey, I just reviewed your patches and looks good to me.

BTW, do you think you could add some documentation on what shim measures and on which PCRs? Thanks!

**Comment by vathpela** [comment]
I've added some PCR docs here: https://github.com/rhboot/shim/pull/89/commits/ab4bfc40e54238975799970696e45ae3b2da754b

**Comment by martinezjavier** [comment]
@vathpela that's great, thanks a lot for adding it.

**Comment by vathpela** [comment]
I've pulled this as part of #89

**Pull request closed without merging**
